### ISSUE TITLE
File titles extremely large

### ISSUE THREAD

**Issue by mpaluta** [hungsu/vileplume-obsidian#10]
In the past month or two, my file names became extremely large in the Vileplume theme and take up a lot of screen space. This is not an H1 heading, but the filename itself. Would it be possible to shrink these back to a smaller size, for example like the Nord theme below?

Example in Vileplume:
![image](https://user-images.githubusercontent.com/12620574/211125729-f5fb69de-1436-4ecd-849b-c467a4d05974.png)

Example in Nord:
![image](https://user-images.githubusercontent.com/12620574/211125720-f09ad5c9-04bf-4369-9d66-aea976e3093b.png)

Thanks!

**Comment by hungsu** [comment]
Hi @mpaluta ! Glad you're still using and enjoying Vileplume!

This should be an easy fix

**Comment by hungsu** [comment]
Please update Vileplume and that should be fixed now :) There's also a Style Setting if you want to fine tune the size

**Comment by mpaluta** [comment]
Thank you!
