### ISSUE TITLE
Lists in edit mode misaligned when wrapping

### ISSUE THREAD

**Issue by Ampa** [hungsu/vileplume-obsidian#4]
![Misaligned](https://user-images.githubusercontent.com/1459388/114101660-eef1d880-98bd-11eb-9cfd-f69b3c8d6d12.png)

![Aligned](https://user-images.githubusercontent.com/1459388/114101689-fe712180-98bd-11eb-8b92-1d1fd4cddd03.png)

Hopefully the images show the issue.

The left edge of lists is misaligned when the line wraps in the editor view.

Thanks for the great theme. Really crisp!

**Comment by hungsu** [comment]
Hi there! Thanks so much for filing the issue and the great screenshots, this should now be fixed! Please update the theme by clicking "Use" on it again in Community themes - and if it isn't fixed please let me know :)

![image](https://user-images.githubusercontent.com/1990680/114129221-feb7ef80-98b2-11eb-8490-d43fddce58ee.png)

**Comment by Ampa** [comment]
OMG! So quick!

Thank you. Seems to work perfectly.

I'll take a look at what you changed to see if I can learn the mysteries of CSS in Codemirror.
