### ISSUE TITLE
Will this be updated to 1.0?

### ISSUE THREAD

**Issue by valevasqc** [hungsu/vileplume-obsidian#9]
I love the theme, but it's still legacy :(

**Comment by hungsu** [comment]
Hi @valevasqc , that doesn't sound right. Can you try uninstalling and installing again? This was updated for 1.0 quite a long time ago

**Comment by valevasqc** [comment]
Hi! I'm so sorry, I have no idea why this theme was the only one that didn't update. Uninstalling and installing worked, thank you!

**Comment by hungsu** [comment]
@valevasqc oh don't even worry about it! It's actually refreshing to know people still use this - I had forgotten about it, and just noticed the H1 text is quite small so changed it back to the old big size. Glad you're enjoying Vileplume!
